name: Update IPTV List

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repo
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar requests
        run: pip install requests

      - name: Ejecutar script
        run: python script.py

      - name: Subir lista
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@github.com"
          git add lista.m3u
          git commit -m "update lista" || echo "sin cambios"
          git push
